- pom.xml
- src/main/java/com/descope/exception/ServerCommonException.java
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/flow/FlowMetadata.java
- src/main/java/com/descope/model/flow/FlowsResponse.java
- src/main/java/com/descope/model/flow/ThemeResponse.java
- src/main/java/com/descope/proxy/impl/AbstractProxyImpl.java
- src/main/java/com/descope/sdk/mgmt/FlowService.java
- src/main/java/com/descope/sdk/mgmt/impl/FlowServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/FlowServiceImplTest.java
Also, add way to debug print response as well as parse nginx unstructured responses
> Add list flows and minor fix to theme export

- examples/management-cli/src/main/java/com/descope/AccessKeyCreate.java
Small fix to the examples after dependency update
> Update dependency and fix compile err

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/sdk/SdkServicesBase.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
> Make sure to encode URL params

- src/main/java/com/descope/model/user/request/UserSearchRequest.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
+ test 
related to https://github.com/descope/etc/issues/4154
> Search users by phone or emails

- src/main/java/com/descope/client/Config.java
- src/main/java/com/descope/client/DescopeClient.java
- src/main/java/com/descope/literals/AppConstants.java
- src/main/java/com/descope/utils/EnvironmentUtils.java
- src/test/java/com/descope/sdk/TestUtils.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
So now we can more easily run tests against different env
> Make base URL configurable from env var

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/enums/NodeExpressionType.java
- src/main/java/com/descope/enums/NodeType.java
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/authz/HasRelationsResponse.java
- src/main/java/com/descope/model/authz/LoadSchemaResponse.java
- src/main/java/com/descope/model/authz/Namespace.java
- src/main/java/com/descope/model/authz/Node.java
- src/main/java/com/descope/model/authz/NodeExpression.java
- src/main/java/com/descope/model/authz/Relation.java
- src/main/java/com/descope/model/authz/RelationDefinition.java
- src/main/java/com/descope/model/authz/RelationQuery.java
- src/main/java/com/descope/model/authz/RelationsResponse.java
- src/main/java/com/descope/model/authz/Schema.java
- src/main/java/com/descope/model/authz/UserQuery.java
- src/main/java/com/descope/model/authz/WhoCanAccessResponse.java
- src/main/java/com/descope/model/mgmt/ManagementServices.java
- src/main/java/com/descope/sdk/mgmt/AuthzService.java
- src/main/java/com/descope/sdk/mgmt/impl/AuthzServiceImpl.java
- src/main/java/com/descope/sdk/mgmt/impl/ManagementServiceBuilder.java
- src/test/data/files.yaml
- src/test/java/com/descope/sdk/mgmt/impl/AuthzServiceImplTest.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
Support for authz management APIs
> Authz support

- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/user/request/UserRequest.java
- src/main/java/com/descope/sdk/mgmt/UserService.java
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
Support with both user ID and login ID
related to https://github.com/descope/etc/issues/4121
> Logout all devices call

- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/user/response/ProviderTokenResponse.java
- src/main/java/com/descope/sdk/mgmt/UserService.java
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
Fixes https://github.com/descope/etc/issues/4610
Add getProviderToken API to user management
> Add getProviderToken API to user management

- README.md
- src/main/java/com/descope/sdk/mgmt/ProjectService.java
Improve clone project comment to mention that this action is supported only with pro license or above
> improve clone project comment

- src/main/java/com/descope/model/mgmt/AccessKeyResponseDetails.java
related to https://github.com/descope/etc/issues/4507
> Expose client ID of access key

- src/main/java/com/descope/model/user/request/UserRequest.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
related to https://github.com/descope/etc/issues/4570
Support additional login ids to user mgmt api
> Support additional login ids

- .github/workflows/ci.yaml
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/flow/Theme.java
- src/main/java/com/descope/proxy/impl/AbstractProxyImpl.java
- src/main/java/com/descope/sdk/mgmt/UserService.java
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
On top of the existing add, remove
+ test
related to https://github.com/descope/etc/issues/4886
> Set user roles

- README.md
- src/main/java/com/descope/sdk/auth/AuthenticationService.java
- src/main/java/com/descope/sdk/auth/impl/AuthenticationServiceImpl.java
- src/test/java/com/descope/sdk/auth/impl/AuthenticationServiceImplTest.java
fixes https://github.com/descope/etc/issues/4847
expose functions to get matched roles / permissions
> Get matched roles and permissions

- README.md
Fixes <link_to_github_issue>
| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |
Added tenant custom attributes and search to readme
> Added tenant custom attributes and search to readme

- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
Forgot to include the user details in the invite request
> fixed invite to include the original request

- examples/management-cli/pom.xml
- pom.xml
> bump version for release

- README.md
- src/main/java/com/descope/enums/DeliveryMethod.java
- src/main/java/com/descope/model/magiclink/request/UpdateEmailRequest.java
- src/main/java/com/descope/model/magiclink/request/UpdatePhoneRequest.java
- src/main/java/com/descope/model/otp/UpdateEmailRequestBody.java
- src/main/java/com/descope/model/otp/UpdatePhoneRequestBody.java
- src/main/java/com/descope/model/password/AuthenticationPasswordResetRequestBody.java
- src/main/java/com/descope/sdk/auth/EnchantedLinkService.java
- src/main/java/com/descope/sdk/auth/MagicLinkService.java
- src/main/java/com/descope/sdk/auth/OTPService.java
- src/main/java/com/descope/sdk/auth/PasswordService.java
- src/main/java/com/descope/sdk/auth/impl/AuthenticationsBase.java
- src/main/java/com/descope/sdk/auth/impl/EnchantedLinkServiceImpl.java
- src/main/java/com/descope/sdk/auth/impl/MagicLinkServiceImpl.java
- src/main/java/com/descope/sdk/auth/impl/OTPServiceImpl.java
- src/main/java/com/descope/sdk/auth/impl/PasswordServiceImpl.java
- src/test/java/com/descope/sdk/auth/impl/OTPServiceImplTest.java
https://github.com/descope/etc/issues/2668
Add voice method and templateOptions where relevant.
> Add voice method to OTP and add templateOptions

- src/main/java/com/descope/sdk/auth/impl/SAMLServiceImpl.java
> Fix tenant name arg in saml start

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/model/auth/SAMLResponse.java
- src/main/java/com/descope/sdk/auth/impl/SAMLServiceImpl.java
- src/test/java/com/descope/sdk/auth/impl/SamlLinkServiceImplTest.java
Tested locally and I get the redirect URL
> Fix saml start

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
Fixes https://github.com/descope/etc/issues/6267
add tenantId to the request to remove tenants roles
> fix remove tenant roles

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/model/tenant/TenantSettings.java
- src/main/java/com/descope/sdk/mgmt/impl/TenantServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/TenantServiceImplTest.java
Allow configuring the JIT update of attributes for SAML and OIDC tenants via API
> Tenant jit disabled

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/enums/TenantAuthType.java
- src/main/java/com/descope/model/tenant/TenantSettings.java
- src/main/java/com/descope/sdk/mgmt/impl/TenantServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/TenantServiceImplTest.java
Fixes https://github.com/descope/etc/issues/6483
Add tenant authType to the settings
> Add authType to tenant settings

- src/main/java/com/descope/sdk/auth/TOTPService.java
- src/main/java/com/descope/sdk/auth/impl/TOTPServiceImpl.java
> Add refresh token to TOTP sign in

- examples/management-cli/pom.xml
- pom.xml
> Bump version 1.0.24

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/sdk/auth/TOTPService.java
- src/main/java/com/descope/sdk/auth/impl/TOTPServiceImpl.java
Fixes https://github.com/descope/etc/issues/6673
> Add refresh token to TOTP update user

- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/model/sso/SSOSAMLSettings.java
- src/main/java/com/descope/model/sso/SSOSAMLSettingsByMetadata.java
- src/main/java/com/descope/model/sso/SSOSAMLSettingsResponse.java
- src/test/java/com/descope/sdk/TestUtils.java
- src/test/java/com/descope/sdk/mgmt/impl/SsoServiceImplTest.java
Related to https://github.com/descope/etc/issues/6230
> Add sign key and encryption key configuration to SAML SSO settings

- README.md
- examples/management-cli/pom.xml
- pom.xml
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/user/request/PatchUserRequest.java
- src/main/java/com/descope/model/user/request/UserRequest.java
- src/main/java/com/descope/proxy/ApiProxy.java
- src/main/java/com/descope/proxy/impl/AbstractProxyImpl.java
- src/main/java/com/descope/proxy/impl/ApiProxyImpl.java
- src/main/java/com/descope/sdk/mgmt/UserService.java
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
Related to https://github.com/descope/etc/issues/6646
> Add Patch users

- src/main/java/com/descope/model/ssoapp/OIDCApplicationRequest.java
- src/main/java/com/descope/model/ssoapp/SAMLApplicationRequest.java
- src/main/java/com/descope/model/ssoapp/SSOApplicationOIDCSettings.java
- src/main/java/com/descope/model/ssoapp/SSOApplicationSAMLSettings.java
Related to https://github.com/descope/etc/issues/7014
> Add SAML IDP logout url (+DefaultRelayState +ForceAuthentication)

- src/main/java/com/descope/model/user/request/UserSearchRequest.java
related to https://github.com/descope/etc/issues/7585
> Allow searching by login ids

- src/main/java/com/descope/model/user/response/UsersBatchResponse.java
So we can see which users failed on the invite sent and which not
> Expose additional errors on invite batch

- README.md
- examples/management-cli/pom.xml
- examples/management-cli/src/main/java/com/descope/AuditCreate.java
- examples/management-cli/src/main/java/com/descope/UserCreate.java
- examples/management-cli/src/main/java/com/descope/UserUpdate.java
- pom.xml
Update dependencies in pom.xml and also make sure to take latest in the examples pom.
Related to https://github.com/descope/descope-java/issues/143
> Update dependencies and fix README

- src/main/java/com/descope/literals/Routes.java
Updates the version for the Management User Add Tenant Roles API. 
With this new version, roles will be added to the tenant even if the user does not have access to the tenant. Access to the tenant will be added.
> Management User Add Tenant Roles API upgrade

- examples/check-pwd-policy/pom.xml
- examples/check-pwd-policy/src/main/java/com/descope/CheckPwdPolicy.java
- pom.xml
- src/main/java/com/descope/model/user/request/UserSearchRequest.java
- src/main/java/com/descope/utils/InstantToMillisSerializer.java
- src/test/java/com/descope/model/user/request/UserSearchRequestTest.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
1. Added search users by createdTime and modifiedTime
2. Added a simple example of checking password policy
> Added search users by createdTime and modifiedTime

- examples/management-cli/src/main/java/com/descope/JwtSignIn.java
- examples/management-cli/src/main/java/com/descope/JwtSignUp.java
- examples/management-cli/src/main/java/com/descope/JwtSignUpOrIn.java
- examples/management-cli/src/main/java/com/descope/ManagementCLI.java
- pom.xml
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/auth/AuthenticationInfo.java
- src/main/java/com/descope/model/jwt/MgmtSignUpUser.java
- src/main/java/com/descope/model/jwt/request/ManagementSignInRequest.java
- src/main/java/com/descope/model/jwt/request/ManagementSignUpRequest.java
- src/main/java/com/descope/model/magiclink/LoginOptions.java
- src/main/java/com/descope/sdk/mgmt/JwtService.java
- src/main/java/com/descope/sdk/mgmt/impl/JwtServiceImpl.java
- src/test/java/com/descope/sdk/TestUtils.java
- src/test/java/com/descope/sdk/auth/impl/WebAuthnServiceImplTest.java
- src/test/java/com/descope/sdk/mgmt/impl/JwtServiceImplSignInSignUpTest.java
Resolves https://github.com/descope/etc/issues/9705
Adding the 3 "management login" APIs to the Java SDK: signIn, signUp & signUpOrIn, including CLI examples
> Support mgmt login apis

- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/mgmt/ManagementServices.java
- src/main/java/com/descope/model/outbound/DeleteOutboundAppUserTokensRequest.java
- src/main/java/com/descope/model/outbound/FetchOutboundAppTokenOptions.java
- src/main/java/com/descope/model/outbound/FetchOutboundAppUserTokenRequest.java
- src/main/java/com/descope/model/outbound/FetchOutboundAppUserTokenResponse.java
- src/main/java/com/descope/model/outbound/OutboundAppToken.java
- src/main/java/com/descope/model/user/request/UserSearchRequest.java
- src/main/java/com/descope/sdk/mgmt/OutboundAppsService.java
- src/main/java/com/descope/sdk/mgmt/impl/ManagementServiceBuilder.java
- src/main/java/com/descope/sdk/mgmt/impl/OutboundAppsServiceImpl.java
- src/test/java/com/descope/model/user/request/UserSearchRequestTest.java
- src/test/java/com/descope/sdk/mgmt/impl/OutboundAppsServiceImplTest.java
Fixes https://github.com/descope/etc/issues/9743
Added token management for outbound apps - initial implementation
> Added token management for outbound apps

- src/main/java/com/descope/sdk/auth/OAuthService.java
- src/main/java/com/descope/sdk/auth/impl/OAuthServiceImpl.java
- src/test/java/com/descope/sdk/auth/impl/OAuthServiceImplTest.java
+ test 
fixes https://github.com/descope/etc/issues/10021
> Add url auth params to oauth methods

- pom.xml
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/inbound/InboundApp.java
- src/main/java/com/descope/model/inbound/InboundAppConsent.java
- src/main/java/com/descope/model/inbound/InboundAppConsentDeleteOptions.java
- src/main/java/com/descope/model/inbound/InboundAppConsentSearchOptions.java
- src/main/java/com/descope/model/inbound/InboundAppConsentSearchResponse.java
- src/main/java/com/descope/model/inbound/InboundAppCreateResponse.java
- src/main/java/com/descope/model/inbound/InboundAppRequest.java
- src/main/java/com/descope/model/inbound/InboundAppScope.java
- src/main/java/com/descope/model/inbound/InboundAppSecret.java
- src/main/java/com/descope/model/inbound/InboundAppTenantConsentDeleteOptions.java
- src/main/java/com/descope/model/inbound/LoadAllApplicationsResponse.java
- src/main/java/com/descope/model/mgmt/ManagementServices.java
- src/main/java/com/descope/sdk/mgmt/InboundAppsService.java
- src/main/java/com/descope/sdk/mgmt/impl/InboundAppsServiceImpl.java
- src/main/java/com/descope/sdk/mgmt/impl/ManagementServiceBuilder.java
- src/test/java/com/descope/sdk/mgmt/impl/InboundAppsServiceImplTest.java
+ tests 
fixes https://github.com/descope/etc/issues/10077
> Inbound app support

- README.md
- pom.xml
- src/main/java/com/descope/model/auth/InviteOptions.java
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
Fixes https://github.com/descope/etc/issues/10283
Add map of template option strings to invite user and batch invite
> Add map of template option strings to invite user

- pom.xml
- src/main/java/com/descope/utils/JwtUtils.java
Fixes https://github.com/descope/etc/issues/10399
Update jsonwebtoken to new version
> update jsonwebtoken to new version

- src/main/java/com/descope/model/jwt/request/ManagementSignInRequest.java
- src/main/java/com/descope/model/magiclink/LoginOptions.java
- src/main/java/com/descope/sdk/auth/EnchantedLinkService.java
- src/main/java/com/descope/sdk/mgmt/TenantService.java
- src/main/java/com/descope/sdk/mgmt/UserService.java
- src/main/java/com/descope/sdk/mgmt/impl/JwtServiceImpl.java
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
+ tests 
related to https://github.com/descope/etc/issues/10553
> Allow logout according to types

- src/main/java/com/descope/exception/ClientFunctionalException.java
Fixes https://github.com/descope/etc/issues/10995
| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |
Added logging of root cause if JWT validation fails.
> fix: Add Cause to Error Log for JWT Validation

- pom.xml
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/customattributes/CreateCustomAttributesRequest.java
- src/main/java/com/descope/model/customattributes/CustomAttribute.java
- src/main/java/com/descope/model/customattributes/CustomAttributeOption.java
- src/main/java/com/descope/model/customattributes/CustomAttributesResponse.java
- src/main/java/com/descope/model/customattributes/DeleteCustomAttributesRequest.java
- src/main/java/com/descope/model/mgmt/ManagementServices.java
- src/main/java/com/descope/sdk/mgmt/UserCustomAttributesService.java
- src/main/java/com/descope/sdk/mgmt/impl/ManagementServiceBuilder.java
- src/main/java/com/descope/sdk/mgmt/impl/UserCustomAttributesServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/UserCustomAttributesServiceImplTest.java
+ tests 
fixes https://github.com/descope/etc/issues/11122
> Expose create and Delete csutom attributes

- pom.xml
- src/main/java/com/descope/model/user/request/BatchUserPasswordBuddyauth.java
- src/main/java/com/descope/model/user/request/BatchUserPasswordHashed.java
Fixes <https://github.com/descope/etc/issues/11189> 
| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |
Added BuddyAuth hashing to the Batch Create User.
> Adding BuddyAuth Hashing to Create Batch User

- README.md
Fixes https://github.com/descope/etc/issues/11089
Added documentation for inbound and outbound app management methods in the readme.
> Update readme with inbound and outbound app management methods

- src/main/java/com/descope/sdk/mgmt/TenantService.java
Fixes https://github.com/descope/descope-java/pull/219#discussion_r2227540705
id -> tenantId parameter in revokeSSOConfigurationLink
> id -> tenantId in revokeSSOConfigurationLink

- pom.xml
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/jwt/request/AnonymousUserRequest.java
- src/main/java/com/descope/sdk/mgmt/JwtService.java
- src/main/java/com/descope/sdk/mgmt/impl/JwtServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/JwtServiceImplTest.java
> Create anonymous users

- pom.xml
- src/main/java/com/descope/model/user/request/UserSearchRequest.java
- src/test/java/com/descope/model/user/request/UserSearchRequestTest.java
- src/test/java/com/descope/sdk/mgmt/impl/OutboundAppsByTokenServiceImplTest.java
Allow user search by role names instead of IDs
> User search by role names instead of ids

- pom.xml
- src/main/java/com/descope/model/mgmt/AccessKeyResponseDetails.java
- src/main/java/com/descope/model/mgmt/AccessKeyUpdateRequest.java
- src/main/java/com/descope/sdk/mgmt/AccessKeyService.java
- src/main/java/com/descope/sdk/mgmt/impl/AccessKeyServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/AccessKeyServiceImplTest.java
fixes https://github.com/descope/descope-java/issues/236
> Add more option to acceess key create/update

- src/main/java/com/descope/model/user/request/UserSearchRequest.java
- src/test/java/com/descope/model/user/request/UserSearchRequestTest.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
Fixes https://github.com/descope/etc/issues/11969
Fixes https://github.com/descope/etc/issues/11946
Add text to user search
> Add text to user search

- README.md
- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/sdk/auth/AuthenticationService.java
- src/main/java/com/descope/sdk/auth/impl/AuthenticationServiceImpl.java
- src/test/java/com/descope/sdk/auth/impl/AuthenticationServiceImplTest.java
Fixes https://github.com/descope/etc/issues/11607.
Select an active tenant
> Add AuthenticationService#selectTenant()

- README.md
- pom.xml
- src/main/java/com/descope/model/user/request/UserRequest.java
- src/main/java/com/descope/sdk/mgmt/UserService.java
- src/main/java/com/descope/sdk/mgmt/impl/UserServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/InboundAppsServiceImplTest.java
- src/test/java/com/descope/sdk/mgmt/impl/UserServiceImplTest.java
related [<>](https://authtown.slack.com/archives/C063Z0WBGKB/p1758876748199729?thread_ts=1755611194.456749&cid=C063Z0WBGKB)
1. fix readme user tenants
2. update additionalIdentifiers name
3. apply user id to patch and update
> update and fix user update api

- src/main/java/com/descope/literals/Routes.java
- src/main/java/com/descope/model/authz/ResourcesResponse.java
- src/main/java/com/descope/sdk/mgmt/AuthzService.java
- src/main/java/com/descope/sdk/mgmt/impl/AuthzServiceImpl.java
- src/test/java/com/descope/sdk/mgmt/impl/AuthzServiceImplTest.java
Fixes https://github.com/descope/etc/issues/12340
Add the FGA API `whatCanTargetAccessWithRelation`
> Add the FGA API whatCanTargetAccessWithRelation
